import type {
  ActivityRun,
  AdapterStatus,
  ContextEntry,
  ContextPack,
  DashboardSnapshot,
  DiagnosticCheck,
  DiagnosticsReport,
  PrivacySummary,
  ReviewItem,
  ReviewPolicy,
  RevisionEntry,
  Settings,
  WorkspaceNode,
} from '../types'

export const MOCK_GLOBAL_SCOPE_ID = 'global:global'
export const MOCK_PROJECT_SCOPE_ID = 'project:/Users/mock/Atlas'
export const MOCK_TASK_SCOPE_ID = 'task:release-candidate'

const workspace: WorkspaceNode[] = [
  {
    id: MOCK_GLOBAL_SCOPE_ID,
    label: 'Shared operating context',
    kind: 'global',
    description: 'Context intentionally available across all registered projects.',
    status: 'Healthy',
    children: [],
  },
  {
    id: MOCK_PROJECT_SCOPE_ID,
    label: 'Atlas Desktop',
    kind: 'project',
    description: 'The registered Atlas repository on this Mac.',
    status: 'Needs review',
    children: [
      {
        id: MOCK_TASK_SCOPE_ID,
        label: 'Release candidate',
        kind: 'task',
        description: 'Derived task context for the current release run.',
        status: 'Derived',
        children: [],
      },
    ],
  },
]

const packs: ContextPack[] = [
  {
    id: 'pack-global-guardrails',
    scopeId: MOCK_GLOBAL_SCOPE_ID,
    scopeKind: 'global',
    scopeLabel: 'Shared operating context',
    name: 'Operator guardrails',
    status: 'active',
    tokenEstimate: 266,
    updatedAt: '2026-08-28T22:21:00Z',
    summary: 'Two durable entries for safety and editorial defaults.',
    tags: ['policy', 'safety'],
    body: 'Safety boundaries and response defaults.',
    provenance: ['desktop/manual', 'AGENTS.md'],
    revision: 8,
  },
  {
    id: 'pack-project-workflow',
    scopeId: MOCK_PROJECT_SCOPE_ID,
    scopeKind: 'project',
    scopeLabel: 'Atlas Desktop',
    name: 'Repository workflow',
    status: 'active',
    tokenEstimate: 318,
    updatedAt: '2026-08-28T23:42:00Z',
    summary: 'Markdown testing guidance and structured tool preferences.',
    tags: ['workflow', 'testing', 'tools'],
    body: 'Repository workflow entries.',
    provenance: ['AGENTS.md', '.github/copilot-instructions.md'],
    revision: 12,
  },
  {
    id: 'pack-task-release',
    scopeId: MOCK_TASK_SCOPE_ID,
    scopeKind: 'task',
    scopeLabel: 'Release candidate',
    name: 'Release desk',
    status: 'active',
    tokenEstimate: 174,
    updatedAt: '2026-08-29T00:02:00Z',
    summary: 'Derived task checklist for the release candidate.',
    tags: ['release', 'derived'],
    body: 'Release task context.',
    provenance: ['runs/release-42'],
    revision: 4,
  },
]

const entries: ContextEntry[] = [
  {
    id: 'entry-global-safety',
    packId: 'pack-global-guardrails',
    packName: 'Operator guardrails',
    packKey: 'operator-guardrails',
    scopeId: MOCK_GLOBAL_SCOPE_ID,
    scopeKind: 'global',
    scopeLabel: 'Shared operating context',
    key: 'safety-boundaries',
    title: 'Safety boundaries',
    kind: 'instruction',
    format: 'markdown',
    body:
      'Keep durable context local by default. Require explicit confirmation for destructive or broad mutations.',
    renderedBody:
      'Keep durable context local by default. Require explicit confirmation for destructive or broad mutations.',
    tags: ['safety', 'local-first'],
    locked: true,
    status: 'active',
    provenance: {
      actor: 'desktop-operator',
      source: 'desktop_editor',
      note: 'Reviewed operating boundary.',
    },
    revision: 5,
    createdAt: '2026-08-21T18:30:00Z',
    updatedAt: '2026-08-28T22:21:00Z',
  },
  {
    id: 'entry-global-voice',
    packId: 'pack-global-guardrails',
    packName: 'Operator guardrails',
    packKey: 'operator-guardrails',
    scopeId: MOCK_GLOBAL_SCOPE_ID,
    scopeKind: 'global',
    scopeLabel: 'Shared operating context',
    key: 'response-defaults',
    title: 'Response defaults',
    kind: 'preference',
    format: 'json',
    body: '{\n  "tone": "concise",\n  "showSources": true,\n  "maxBullets": 7\n}',
    renderedBody: '{\n  "tone": "concise",\n  "showSources": true,\n  "maxBullets": 7\n}',
    jsonValue: { tone: 'concise', showSources: true, maxBullets: 7 },
    tags: ['voice', 'json'],
    locked: false,
    status: 'active',
    provenance: {
      actor: 'desktop-operator',
      source: 'desktop_editor',
      sourceRef: 'preferences.json',
    },
    revision: 3,
    createdAt: '2026-08-22T15:11:00Z',
    updatedAt: '2026-08-28T21:05:00Z',
  },
  {
    id: 'entry-project-testing',
    packId: 'pack-project-workflow',
    packName: 'Repository workflow',
    packKey: 'repository-workflow',
    scopeId: MOCK_PROJECT_SCOPE_ID,
    scopeKind: 'project',
    scopeLabel: 'Atlas Desktop',
    key: 'focused-testing',
    title: 'Focused testing',
    kind: 'instruction',
    format: 'markdown',
    body:
      'Run the smallest targeted test first, then lint and build the desktop package before handing off.',
    renderedBody:
      'Run the smallest targeted test first, then lint and build the desktop package before handing off.',
    tags: ['testing', 'quality'],
    locked: false,
    status: 'active',
    provenance: {
      actor: 'source-import',
      source: 'agents_md',
      sourceRef: '/Users/mock/Atlas/AGENTS.md',
      requestId: 'request-import-41',
    },
    revision: 7,
    createdAt: '2026-08-23T11:00:00Z',
    updatedAt: '2026-08-28T23:42:00Z',
  },
  {
    id: 'entry-project-tools',
    packId: 'pack-project-workflow',
    packName: 'Repository workflow',
    packKey: 'repository-workflow',
    scopeId: MOCK_PROJECT_SCOPE_ID,
    scopeKind: 'project',
    scopeLabel: 'Atlas Desktop',
    key: 'tool-preferences',
    title: 'Tool preferences',
    kind: 'configuration',
    format: 'json',
    body:
      '{\n  "packageManager": "pnpm",\n  "testCommand": "pnpm test",\n  "buildCommand": "pnpm build"\n}',
    renderedBody:
      '{\n  "packageManager": "pnpm",\n  "testCommand": "pnpm test",\n  "buildCommand": "pnpm build"\n}',
    jsonValue: {
      packageManager: 'pnpm',
      testCommand: 'pnpm test',
      buildCommand: 'pnpm build',
    },
    tags: ['tools', 'json'],
    locked: false,
    status: 'active',
    provenance: {
      actor: 'source-import',
      source: 'copilot_instructions',
      sourceRef: '/Users/mock/Atlas/.github/copilot-instructions.md',
      requestId: 'request-import-41',
    },
    revision: 4,
    createdAt: '2026-08-23T11:01:00Z',
    updatedAt: '2026-08-28T23:38:00Z',
  },
  {
    id: 'entry-project-retired',
    packId: 'pack-project-workflow',
    packName: 'Repository workflow',
    packKey: 'repository-workflow',
    scopeId: MOCK_PROJECT_SCOPE_ID,
    scopeKind: 'project',
    scopeLabel: 'Atlas Desktop',
    key: 'retired-release-note',
    title: 'Retired release note',
    kind: 'note',
    format: 'markdown',
    body: 'This archived entry remains available for history and restoration.',
    renderedBody: 'This archived entry remains available for history and restoration.',
    tags: ['archived'],
    locked: false,
    status: 'deleted',
    provenance: {
      actor: 'desktop-operator',
      source: 'desktop_editor',
      note: 'Archived after the previous release.',
    },
    revision: 2,
    createdAt: '2026-08-19T09:12:00Z',
    updatedAt: '2026-08-27T17:20:00Z',
  },
  {
    id: 'entry-task-checklist',
    packId: 'pack-task-release',
    packName: 'Release desk',
    packKey: 'release-desk',
    scopeId: MOCK_TASK_SCOPE_ID,
    scopeKind: 'task',
    scopeLabel: 'Release candidate',
    key: 'release-checklist',
    title: 'Release checklist',
    kind: 'checklist',
    format: 'markdown',
    body:
      'Validate import previews, inspect diagnostics, and keep the review queue clear before tagging.',
    renderedBody:
      'Validate import previews, inspect diagnostics, and keep the review queue clear before tagging.',
    tags: ['release', 'derived'],
    locked: false,
    status: 'active',
    provenance: {
      actor: 'release-agent',
      source: 'run',
      runId: 'run-release-42',
      note: 'Derived from the current task run.',
    },
    revision: 4,
    createdAt: '2026-08-28T19:00:00Z',
    updatedAt: '2026-08-29T00:02:00Z',
  },
]

const reviewQueue: ReviewItem[] = [
  {
    id: 'review-a-conflict',
    requestId: 'request-agent-71',
    packId: 'pack-project-workflow',
    packName: 'Repository workflow',
    scopeId: MOCK_PROJECT_SCOPE_ID,
    scopeKind: 'project',
    scopeLabel: 'Atlas Desktop',
    entryKey: 'focused-testing',
    title: 'Expand focused test guidance',
    summary: 'An existing entry would change under balanced or strict review policy.',
    requestedBy: 'coding-agent',
    requestedAt: '2026-08-28T23:52:00Z',
    ageSeconds: 3_000,
    risk: 'medium',
    reason: 'conflict',
    diff: 'Existing and proposed content differ.',
    diffSides: {
      before:
        'Run the smallest targeted test first, then lint and build the desktop package before handing off.',
      after:
        'Run the smallest targeted test first. If it passes, run desktop lint and build before handing off.',
      format: 'markdown',
      changed: true,
    },
    existingContent:
      'Run the smallest targeted test first, then lint and build the desktop package before handing off.',
    proposedContent:
      'Run the smallest targeted test first. If it passes, run desktop lint and build before handing off.',
    provenance: {
      actor: 'coding-agent',
      source: 'post_work',
      sourceRef: 'session-71',
      runId: 'run-agent-71',
      requestId: 'request-agent-71',
    },
    source: 'post_work',
    suggestedEdit:
      'Run the smallest targeted test first. If it passes, run desktop lint and build before handing off.',
  },
  {
    id: 'review-b-strict',
    requestId: 'request-import-43',
    packId: 'pack-project-workflow',
    packName: 'Repository workflow',
    scopeId: MOCK_PROJECT_SCOPE_ID,
    scopeKind: 'project',
    scopeLabel: 'Atlas Desktop',
    entryKey: 'accessibility-check',
    title: 'Add accessibility check',
    summary: 'Strict policy queues new project instructions for approval.',
    requestedBy: 'source-import',
    requestedAt: '2026-08-28T20:30:00Z',
    ageSeconds: 15_000,
    risk: 'low',
    reason: 'strict_policy',
    diff: 'A new entry is proposed.',
    diffSides: {
      after: 'Verify keyboard operation, VoiceOver labels, focus order, and reduced motion.',
      format: 'markdown',
      changed: true,
    },
    proposedContent:
      'Verify keyboard operation, VoiceOver labels, focus order, and reduced motion.',
    provenance: {
      actor: 'source-import',
      source: 'copilot_instructions',
      sourceRef: '/Users/mock/Atlas/.github/copilot-instructions.md',
      requestId: 'request-import-43',
    },
    source: 'copilot_instructions',
    suggestedEdit:
      'Verify keyboard operation, VoiceOver labels, focus order, and reduced motion.',
  },
  {
    id: 'review-c-partial-offline',
    requestId: 'request-spool-9',
    packId: 'pack-task-release',
    packName: 'Release desk',
    scopeId: MOCK_TASK_SCOPE_ID,
    scopeKind: 'task',
    scopeLabel: 'Release candidate',
    entryKey: 'release-checklist',
    title: 'Queued write from an offline adapter',
    summary: 'This fixture intentionally fails during bulk triage after earlier items succeed.',
    requestedBy: 'offline-adapter',
    requestedAt: '2026-08-26T19:00:00Z',
    ageSeconds: 192_000,
    risk: 'high',
    reason: 'locked',
    diff: 'An unavailable adapter cannot complete this review.',
    diffSides: {
      before:
        'Validate import previews, inspect diagnostics, and keep the review queue clear before tagging.',
      after:
        'Validate import previews, inspect diagnostics, clear the review queue, and verify adapter recovery before tagging.',
      format: 'markdown',
      changed: true,
    },
    existingContent:
      'Validate import previews, inspect diagnostics, and keep the review queue clear before tagging.',
    proposedContent:
      'Validate import previews, inspect diagnostics, clear the review queue, and verify adapter recovery before tagging.',
    provenance: {
      actor: 'offline-adapter',
      source: 'spool',
      sourceRef: '/Users/mock/Library/Application Support/UCM/spool/queued-9.json',
      requestId: 'request-spool-9',
    },
    source: 'spool',
    suggestedEdit:
      'Validate import previews, inspect diagnostics, clear the review queue, and verify adapter recovery before tagging.',
  },
]

const activity: ActivityRun[] = [
  {
    id: 'run-release-42',
    actor: 'release-agent',
    summary: 'Composed release context and queued one locked update.',
    status: 'blocked',
    startedAt: '2026-08-28T23:45:00Z',
    durationMs: 1_020_000,
    stepCount: 12,
    contextPackIds: ['pack-global-guardrails', 'pack-project-workflow', 'pack-task-release'],
  },
  {
    id: 'run-import-41',
    actor: 'source-import',
    summary: 'Imported repository instruction sources.',
    status: 'completed',
    startedAt: '2026-08-23T11:00:00Z',
    durationMs: 84_000,
    stepCount: 4,
    contextPackIds: ['pack-project-workflow'],
  },
]

const revisions: RevisionEntry[] = [
  {
    id: 'rev-entry-project-testing-7',
    entityId: 'entry-project-testing',
    entityLabel: 'Focused testing',
    author: 'source-import',
    createdAt: '2026-08-28T23:42:00Z',
    note: 'Refreshed focused test guidance.',
    changeSummary: 'Kept targeted tests ahead of package-wide validation.',
    restorable: true,
  },
  {
    id: 'rev-entry-project-tools-4',
    entityId: 'entry-project-tools',
    entityLabel: 'Tool preferences',
    author: 'source-import',
    createdAt: '2026-08-28T23:38:00Z',
    note: 'Updated structured package commands.',
    changeSummary: 'Stored pnpm test and build commands as JSON.',
    restorable: true,
  },
  {
    id: 'rev-entry-global-safety-5',
    entityId: 'entry-global-safety',
    entityLabel: 'Safety boundaries',
    author: 'desktop-operator',
    createdAt: '2026-08-28T22:21:00Z',
    note: 'Confirmed explicit broad-action review.',
    changeSummary: 'Clarified local storage and confirmation boundaries.',
    restorable: true,
  },
  {
    id: 'rev-policy-review-3',
    entityId: 'review',
    entityLabel: 'Review policy',
    author: 'desktop-operator',
    createdAt: '2026-08-28T18:00:00Z',
    note: 'Selected strict review mode.',
    changeSummary: 'All non-duplicate agent proposals now wait for review.',
    restorable: false,
  },
]

const diagnosticChecks: DiagnosticCheck[] = [
  {
    id: 'daemon-health',
    label: 'Daemon health and schema',
    component: 'daemon',
    state: 'healthy',
    summary: 'The local context daemon is reachable and schema-compatible.',
    details: [
      'Context API version 1; desktop expects 1.',
      'Daemon component version 0.1.0; desktop expects 0.1.0.',
      '3 packs, 6 entries, 3 pending reviews.',
    ],
    path: '/Users/mock/Library/Application Support/UCM/contextd.sock',
    detectedVersion: '6',
    expectedVersion: '6',
    remediation: [
      { id: 'restart-daemon', label: 'Recheck or restart daemon', kind: 'restart_daemon' },
    ],
    checkedAt: '2026-08-29T00:32:00Z',
  },
  {
    id: 'adapter-codex-marker',
    label: 'Codex adapter marker',
    component: 'adapter',
    state: 'degraded',
    summary: 'The adapter marker exists, but one launcher path is stale.',
    details: ['Marker: ~/.codex/config.toml', 'Launcher path requires review.'],
    path: '/Users/mock/.codex/config.toml',
    detectedVersion: '0.1.0',
    expectedVersion: '0.1.0',
    remediation: [
      { id: 'refresh-adapter', label: 'Refresh diagnostics', kind: 'refresh' },
      { id: 'repair-adapter', label: 'Reinstall the local adapter', kind: 'manual' },
    ],
    checkedAt: '2026-08-29T00:32:00Z',
  },
  {
    id: 'adapter-claude-marker',
    label: 'Claude Code adapter marker',
    component: 'adapter',
    state: 'incompatible',
    summary: 'The installed adapter marker reports an incompatible version.',
    details: ['Detected 0.0.8; desktop expects 0.1.0.'],
    path: '/Users/mock/.claude/plugins/installed_plugins.json',
    detectedVersion: '0.0.8',
    expectedVersion: '0.1.0',
    remediation: [
      { id: 'update-adapter', label: 'Install the matching adapter', kind: 'manual' },
    ],
    checkedAt: '2026-08-29T00:32:00Z',
  },
  {
    id: 'binary-contextctl',
    label: 'contextctl binary',
    component: 'binary',
    state: 'not_installed',
    summary: 'contextctl was not found in the application bundle or PATH.',
    details: [],
    expectedVersion: '0.1.0',
    remediation: [
      { id: 'install-binary', label: 'Install the matching local binary', kind: 'manual' },
    ],
    checkedAt: '2026-08-29T00:32:00Z',
  },
  {
    id: 'spool',
    label: 'Failed-write spool',
    component: 'spool',
    state: 'failed',
    summary: 'One queued write remains after its last delivery attempt.',
    details: ['The payload remains local and was not discarded.'],
    path: '/Users/mock/Library/Application Support/UCM/spool',
    remediation: [{ id: 'retry-spool', label: 'Retry queued writes', kind: 'retry_spool' }],
    checkedAt: '2026-08-29T00:32:00Z',
  },
  {
    id: 'socket-starting',
    label: 'Secondary socket probe',
    component: 'daemon',
    state: 'starting',
    summary: 'A recent socket marker is waiting for a health response.',
    details: [],
    remediation: [{ id: 'refresh-starting', label: 'Retry health check', kind: 'refresh' }],
    checkedAt: '2026-08-29T00:32:00Z',
  },
  {
    id: 'legacy-schema',
    label: 'Legacy fixture schema',
    component: 'database',
    state: 'migration_required',
    summary: 'A detached fixture database requires a supported migration.',
    details: ['Detected schema 5; expected 6.'],
    detectedVersion: '5',
    expectedVersion: '6',
    remediation: [
      { id: 'start-for-migration', label: 'Start daemon to run migration', kind: 'start_daemon' },
    ],
    checkedAt: '2026-08-29T00:32:00Z',
  },
  {
    id: 'disabled-marker',
    label: 'Disabled adapter marker',
    component: 'adapter',
    state: 'ignored',
    summary: 'This optional adapter is ignored by local settings.',
    details: [],
    remediation: [],
    checkedAt: '2026-08-29T00:32:00Z',
  },
  {
    id: 'stopped-fixture',
    label: 'Detached daemon fixture',
    component: 'daemon',
    state: 'stopped',
    summary: 'A detached fixture daemon is not running.',
    details: [],
    remediation: [{ id: 'start-fixture', label: 'Start daemon', kind: 'start_daemon' }],
    checkedAt: '2026-08-29T00:32:00Z',
  },
]

const diagnostics: DiagnosticsReport = {
  generatedAt: '2026-08-29T00:32:00Z',
  overallState: 'failed',
  daemonReachable: true,
  componentVersion: '0.1.0',
  apiVersion: 1,
  expectedApiVersion: 1,
  schemaVersion: 6,
  expectedSchemaVersion: 6,
  spoolBacklog: 1,
  checks: diagnosticChecks,
}

const adapters: AdapterStatus[] = [
  {
    id: 'adapter-daemon',
    name: 'Local context daemon',
    kind: 'terminal',
    enabled: true,
    health: 'healthy',
    lastCheckedAt: '2026-08-29T00:32:00Z',
    queueDepth: 0,
    path: '/Users/mock/Library/Application Support/UCM/contextd.sock',
    note: 'Single-writer socket is reachable.',
    state: 'healthy',
    detectedVersion: '0.1.0',
    remediation: [
      { id: 'restart-daemon', label: 'Recheck or restart daemon', kind: 'restart_daemon' },
    ],
  },
  {
    id: 'adapter-codex',
    name: 'Codex',
    kind: 'api',
    enabled: true,
    health: 'degraded',
    lastCheckedAt: '2026-08-29T00:32:00Z',
    queueDepth: 0,
    path: '/Users/mock/.codex/config.toml',
    note: 'Marker found; one launcher path needs attention.',
    state: 'degraded',
    detectedVersion: '0.1.0',
    remediation: [{ id: 'refresh-codex', label: 'Refresh diagnostics', kind: 'refresh' }],
  },
  {
    id: 'adapter-claude',
    name: 'Claude Code',
    kind: 'api',
    enabled: true,
    health: 'offline',
    lastCheckedAt: '2026-08-29T00:32:00Z',
    queueDepth: 0,
    path: '/Users/mock/.claude/plugins/installed_plugins.json',
    note: 'Installed marker is incompatible with this desktop build.',
    state: 'incompatible',
    detectedVersion: '0.0.8',
    remediation: [
      { id: 'update-claude', label: 'Install the matching adapter', kind: 'manual' },
    ],
  },
  {
    id: 'adapter-spool',
    name: 'Failed-write spool',
    kind: 'filesystem',
    enabled: true,
    health: 'degraded',
    lastCheckedAt: '2026-08-29T00:32:00Z',
    queueDepth: 1,
    path: '/Users/mock/Library/Application Support/UCM/spool',
    note: 'One local write is retained for retry.',
    state: 'failed',
    remediation: [{ id: 'retry-spool', label: 'Retry queued writes', kind: 'retry_spool' }],
  },
]

const reviewPolicy: ReviewPolicy = {
  mode: 'strict',
  metadata: { source: 'desktop.governance', note: 'Maximum review visibility.' },
  updatedAt: '2026-08-28T18:00:00Z',
  updatedBy: 'desktop-operator',
  revision: 3,
}

const settings: Settings = {
  theme: 'system',
  autoCompose: true,
  reviewMode: 'strict',
  socketPath: '/Users/mock/Library/Application Support/UCM/contextd.sock',
  launchOnLogin: false,
  telemetry: false,
  maxPreviewTokens: 1_400,
  reviewPolicy,
  onboarding: {
    complete: true,
    inferred: false,
    durableContext: true,
    completedAt: '2026-08-23T11:05:00Z',
    lastProjectPath: '/Users/mock/Atlas',
  },
  lastSelectedScopeId: MOCK_PROJECT_SCOPE_ID,
  lastProjectPath: '/Users/mock/Atlas',
}

export const mockOnboardingStates = {
  fresh: {
    complete: false,
    inferred: false,
    durableContext: false,
  },
  resumed: {
    complete: false,
    inferred: false,
    durableContext: false,
    lastProjectPath: '/Users/mock/Atlas',
  },
  inferredReady: {
    complete: true,
    inferred: true,
    durableContext: true,
    lastProjectPath: '/Users/mock/Atlas',
  },
  inferredBlocked: {
    complete: false,
    inferred: true,
    durableContext: true,
    lastProjectPath: '/Users/mock/Atlas',
  },
  complete: structuredClone(settings.onboarding),
} satisfies Record<string, Settings['onboarding']>

const privacy: PrivacySummary = {
  dataPath: '/Users/mock/Library/Application Support/UniversalContextManager',
  databasePath:
    '/Users/mock/Library/Application Support/UniversalContextManager/context.db',
  socketPath:
    '/Users/mock/Library/Application Support/UniversalContextManager/contextd.sock',
  spoolPath: '/Users/mock/Library/Application Support/UniversalContextManager/spool',
  settingsPath:
    '/Users/mock/Library/Application Support/UniversalContextManager/settings.json',
  localOnlyStatement:
    'UCM stores durable context, reviews, revisions, and queued writes on this device.',
  downstreamAdapterDisclosure:
    'Composed context is disclosed only to locally configured downstream adapter processes; those tools may apply their own network policies.',
  secretScanningStatement:
    'Core secret scanning rejects recognized credential patterns before durable writes and imports.',
  applicationEncryptionBoundary:
    'Application-level encryption at rest is not enabled; UCM relies on operating-system account and filesystem protections.',
  counts: {
    packs: packs.length,
    entries: entries.length,
    reviews: reviewQueue.length,
    runs: activity.length,
    spoolBacklog: diagnostics.spoolBacklog,
  },
  countsAvailable: true,
  countsSource: 'store_stats',
  telemetryEnabled: false,
  networkEgressEnabled: false,
}

export const mockDashboard: DashboardSnapshot = {
  workspace,
  packs,
  entries,
  reviewQueue,
  activity,
  revisions,
  adapters,
  settings,
  reviewPolicy,
  onboarding: settings.onboarding,
  diagnostics,
  privacy,
  stats: {
    activePacks: packs.filter((pack) => pack.status === 'active').length,
    pendingReviews: reviewQueue.length,
    healthyAdapters: adapters.filter((adapter) => adapter.health === 'healthy').length,
    runningAgents: activity.filter((run) => run.status === 'running').length,
  },
  selectedScopeId: MOCK_PROJECT_SCOPE_ID,
  connected: true,
  lastSyncAt: '2026-08-29T00:32:00Z',
  notices: [
    'Task scopes are derived from recorded runs; the desktop does not invent task persistence.',
    'Global and locked agent proposals always wait for review.',
  ],
}

export function cloneMockDashboard(): DashboardSnapshot {
  return structuredClone(mockDashboard)
}
