import type {
  ActivityRun,
  AdapterStatus,
  ContextPack,
  DashboardSnapshot,
  ReviewItem,
  RevisionEntry,
  Settings,
  WorkspaceNode,
} from '../types'

const workspace: WorkspaceNode[] = [
  {
    id: 'global-root',
    label: 'Global context',
    kind: 'global',
    description: 'Repository-wide policies and reusable operating context.',
    status: 'Synced',
    children: [],
  },
  {
    id: 'project-atlas',
    label: 'Atlas IDE',
    kind: 'project',
    description: 'Desktop editor project with local MCP workflows.',
    status: 'Needs review',
    children: [
      {
        id: 'task-atlas-release',
        label: 'Release train',
        kind: 'task',
        description: 'Prepare the August desktop release candidate.',
        status: 'In progress',
        children: [],
      },
      {
        id: 'task-atlas-review',
        label: 'PR #184 review',
        kind: 'task',
        description: 'Context bundle for reviewing the migration PR.',
        status: 'Queued',
        children: [],
      },
    ],
  },
  {
    id: 'project-orbit',
    label: 'Orbit API',
    kind: 'project',
    description: 'Backend indexing and retrieval service.',
    status: 'Healthy',
    children: [
      {
        id: 'task-orbit-incident',
        label: 'Incident 2071',
        kind: 'task',
        description: 'Postmortem and recovery runbook updates.',
        status: 'Monitoring',
        children: [],
      },
    ],
  },
]

const packs: ContextPack[] = [
  {
    id: 'pack-global-guardrails',
    scopeId: 'global-root',
    scopeKind: 'global',
    scopeLabel: 'Global context',
    name: 'Operating guardrails',
    status: 'active',
    tokenEstimate: 180,
    updatedAt: '2026-08-16T17:10:00Z',
    summary: 'Human approval gates, local-first policy, and escalation rules.',
    tags: ['policy', 'governance', 'safety'],
    body:
      'Keep all context local by default, summarize before expanding, and route risky actions through explicit review queues. Capture provenance for every imported snippet.',
    provenance: ['policy/desktop-governance.md', 'docs/local-first-principles.md'],
    revision: 7,
  },
  {
    id: 'pack-global-style',
    scopeId: 'global-root',
    scopeKind: 'global',
    scopeLabel: 'Global context',
    name: 'Preferred toolchain',
    status: 'active',
    tokenEstimate: 132,
    updatedAt: '2026-08-16T18:02:00Z',
    summary: 'Tauri + React + Rust conventions for local operator tooling.',
    tags: ['tooling', 'desktop', 'tauri'],
    body:
      'Favor typed APIs, optimistic local feedback, and explicit adapter health reporting. Use revision history to explain why a pack changed, not just what changed.',
    provenance: ['tooling/desktop-stack.toml', 'notes/frontend-foundations.md'],
    revision: 5,
  },
  {
    id: 'pack-atlas-release',
    scopeId: 'project-atlas',
    scopeKind: 'project',
    scopeLabel: 'Atlas IDE',
    name: 'Release checklist',
    status: 'active',
    tokenEstimate: 228,
    updatedAt: '2026-08-16T21:14:00Z',
    summary: 'Ship checklist and known regression watchpoints for Atlas.',
    tags: ['release', 'checklist', 'atlas'],
    body:
      'Validate migration scripts, exercise import/export on representative packs, and keep review queue depth under five before tagging a release candidate. Call out adapter drift in release notes.',
    provenance: ['projects/atlas/release-plan.md', 'runs/release-dry-run-12.log'],
    revision: 4,
  },
  {
    id: 'pack-atlas-pr',
    scopeId: 'task-atlas-review',
    scopeKind: 'task',
    scopeLabel: 'PR #184 review',
    name: 'Migration review bundle',
    status: 'review',
    tokenEstimate: 276,
    updatedAt: '2026-08-17T00:21:00Z',
    summary: 'Facts and concerns for the schema migration PR review.',
    tags: ['review', 'migration', 'schema'],
    body:
      'Focus on rollback clarity, adapter cache invalidation, and whether restored revisions preserve audit provenance. Flag any commands that mutate context without an approval hop.',
    provenance: ['pulls/184/summary.md', 'db/migrations/20260816.sql', 'adapters/cache-plan.md'],
    revision: 3,
  },
  {
    id: 'pack-atlas-reviewer',
    scopeId: 'task-atlas-review',
    scopeKind: 'task',
    scopeLabel: 'PR #184 review',
    name: 'Reviewer notes draft',
    status: 'draft',
    tokenEstimate: 148,
    updatedAt: '2026-08-17T01:08:00Z',
    summary: 'Draft operator framing for the final approval comment.',
    tags: ['draft', 'review', 'operator'],
    body:
      'Open with user impact, then list blocking issues: stale adapter status after restore, missing empty-state copy, and lack of explicit provenance badges in the review modal.',
    provenance: ['notes/reviewer-brief.md'],
    revision: 2,
  },
  {
    id: 'pack-orbit-incident',
    scopeId: 'task-orbit-incident',
    scopeKind: 'task',
    scopeLabel: 'Incident 2071',
    name: 'Recovery runbook',
    status: 'active',
    tokenEstimate: 192,
    updatedAt: '2026-08-16T15:33:00Z',
    summary: 'Incident response runbook and communication staging notes.',
    tags: ['incident', 'runbook', 'orbit'],
    body:
      'Escalate offline adapters first, then rebuild the FTS index and verify exported archives before reopening ingestion. Keep comms concise and timestamped.',
    provenance: ['services/orbit/postmortem-2071.md', 'ops/runbooks/recovery.md'],
    revision: 6,
  },
]

const reviewQueue: ReviewItem[] = [
  {
    id: 'review-184-guardrail',
    packId: 'pack-atlas-pr',
    packName: 'Migration review bundle',
    scopeId: 'task-atlas-review',
    scopeLabel: 'PR #184 review',
    title: 'Add explicit restore safety note',
    summary: 'Reviewer wants the restore flow to call out immutable audit logs.',
    requestedBy: 'A. Rivera',
    requestedAt: '2026-08-17T01:19:00Z',
    risk: 'medium',
    diff: '- restore revisions\n+ restore revisions and preserve the audit ledger',
    suggestedEdit:
      'Focus on rollback clarity, adapter cache invalidation, and whether restored revisions preserve audit provenance in an immutable audit ledger. Flag any commands that mutate context without an approval hop.',
  },
  {
    id: 'review-184-empty-state',
    packId: 'pack-atlas-reviewer',
    packName: 'Reviewer notes draft',
    scopeId: 'task-atlas-review',
    scopeLabel: 'PR #184 review',
    title: 'Tighten empty-state language',
    summary: 'Make the operator guidance shorter and more actionable.',
    requestedBy: 'K. Shah',
    requestedAt: '2026-08-17T01:42:00Z',
    risk: 'low',
    diff: '- missing empty-state copy\n+ missing actionable empty-state copy with next steps',
    suggestedEdit:
      'Open with user impact, then list blocking issues: stale adapter status after restore, missing actionable empty-state copy with next steps, and lack of explicit provenance badges in the review modal.',
  },
  {
    id: 'review-incident-export',
    packId: 'pack-orbit-incident',
    packName: 'Recovery runbook',
    scopeId: 'task-orbit-incident',
    scopeLabel: 'Incident 2071',
    title: 'Document export checksum verification',
    summary: 'Ops wants a checksum verification step before reopening ingestion.',
    requestedBy: 'NOC bot',
    requestedAt: '2026-08-16T23:05:00Z',
    risk: 'high',
    diff: '- verify exported archives\n+ verify exported archives and compare checksums against last-known-good snapshots',
    suggestedEdit:
      'Escalate offline adapters first, then rebuild the FTS index and verify exported archives with checksums against the last-known-good snapshots before reopening ingestion. Keep comms concise and timestamped.',
  },
]

const activity: ActivityRun[] = [
  {
    id: 'run-2191',
    actor: 'desktop-review-agent',
    summary: 'Composed PR #184 review preview and queued two edits.',
    status: 'running',
    startedAt: '2026-08-17T01:10:00Z',
    durationMs: 548000,
    stepCount: 14,
    contextPackIds: ['pack-atlas-pr', 'pack-atlas-reviewer'],
  },
  {
    id: 'run-2190',
    actor: 'release-operator',
    summary: 'Exported Atlas release snapshot for dry-run validation.',
    status: 'completed',
    startedAt: '2026-08-16T23:42:00Z',
    durationMs: 324000,
    stepCount: 9,
    contextPackIds: ['pack-global-guardrails', 'pack-atlas-release'],
  },
  {
    id: 'run-2188',
    actor: 'orbit-recovery-agent',
    summary: 'Detected offline adapter drift during Incident 2071 recovery.',
    status: 'blocked',
    startedAt: '2026-08-16T20:15:00Z',
    durationMs: 918000,
    stepCount: 11,
    contextPackIds: ['pack-orbit-incident'],
  },
  {
    id: 'run-2184',
    actor: 'context-importer',
    summary: 'Imported context packs from the onboarding archive.',
    status: 'completed',
    startedAt: '2026-08-16T17:30:00Z',
    durationMs: 162000,
    stepCount: 6,
    contextPackIds: ['pack-global-guardrails', 'pack-global-style'],
  },
]

const revisions: RevisionEntry[] = [
  {
    id: 'rev-701',
    entityId: 'pack-atlas-reviewer',
    entityLabel: 'Reviewer notes draft',
    author: 'desktop-review-agent',
    createdAt: '2026-08-17T01:08:00Z',
    note: 'Added operator-centric framing for the approval comment.',
    changeSummary: 'Expanded blocker list and highlighted missing provenance badges.',
    restorable: true,
  },
  {
    id: 'rev-700',
    entityId: 'pack-atlas-pr',
    entityLabel: 'Migration review bundle',
    author: 'schema-bot',
    createdAt: '2026-08-17T00:21:00Z',
    note: 'Refreshed bundle after migration dry run.',
    changeSummary: 'Added rollback focus and approval-hop reminder.',
    restorable: true,
  },
  {
    id: 'rev-698',
    entityId: 'pack-atlas-release',
    entityLabel: 'Release checklist',
    author: 'release-operator',
    createdAt: '2026-08-16T21:14:00Z',
    note: 'Captured adapter drift checks for release notes.',
    changeSummary: 'Added review queue depth threshold.',
    restorable: true,
  },
  {
    id: 'rev-693',
    entityId: 'pack-orbit-incident',
    entityLabel: 'Recovery runbook',
    author: 'orbit-recovery-agent',
    createdAt: '2026-08-16T15:33:00Z',
    note: 'Updated recovery ordering after adapter outage.',
    changeSummary: 'Moved archive verification ahead of ingestion restart.',
    restorable: true,
  },
]

const adapters: AdapterStatus[] = [
  {
    id: 'adapter-codex',
    name: 'Codex plugin',
    kind: 'api',
    enabled: true,
    health: 'healthy',
    lastCheckedAt: '2026-08-17T01:24:00Z',
    queueDepth: 0,
    path: 'plugins/context-manager/.mcp.json',
    note: 'SessionStart context injection and MCP tools are available.',
  },
  {
    id: 'adapter-claude',
    name: 'Claude Code plugin',
    kind: 'api',
    enabled: true,
    health: 'healthy',
    lastCheckedAt: '2026-08-17T01:23:00Z',
    queueDepth: 0,
    path: 'adapters/claude-code/.mcp.json',
    note: 'Shared hooks and post-work commit instructions are synchronized.',
  },
  {
    id: 'adapter-daemon',
    name: 'Local context daemon',
    kind: 'terminal',
    enabled: true,
    health: 'healthy',
    lastCheckedAt: '2026-08-17T01:22:00Z',
    queueDepth: 0,
    path: 'unix://~/Library/Application Support/UniversalContextManager/contextd.sock',
    note: 'Single-writer socket is responding and locked to the current user.',
  },
  {
    id: 'adapter-spool',
    name: 'Failed-write spool',
    kind: 'filesystem',
    enabled: true,
    health: 'healthy',
    lastCheckedAt: '2026-08-17T01:20:00Z',
    queueDepth: 0,
    path: '~/Library/Application Support/UniversalContextManager/spool',
    note: 'No pending post-work commits are waiting for retry.',
  },
]

const settings: Settings = {
  theme: 'system',
  autoCompose: true,
  reviewMode: 'balanced',
  socketPath: '~/Library/Application Support/UniversalContextManager/contextd.sock',
  launchOnLogin: false,
  telemetry: false,
  maxPreviewTokens: 1400,
}

export const mockDashboard: DashboardSnapshot = {
  workspace,
  packs,
  reviewQueue,
  activity,
  revisions,
  adapters,
  settings,
  stats: {
    activePacks: packs.filter((pack) => pack.status === 'active').length,
    pendingReviews: reviewQueue.length,
    healthyAdapters: adapters.filter((adapter) => adapter.health === 'healthy').length,
    runningAgents: activity.filter((run) => run.status === 'running').length,
  },
  selectedScopeId: 'task-atlas-review',
  connected: true,
  lastSyncAt: '2026-08-17T01:24:00Z',
  notices: [
    'Draft packs stay out of composed context until you activate them.',
    'Global and conflicting agent writes always wait for human review.',
  ],
}

export function cloneMockDashboard(): DashboardSnapshot {
  return structuredClone(mockDashboard)
}
